# Configuration file for BigBlueCaptor

[general]
visibility = 0 # Hide or show recording window. Requires Xephyr.
resolution = [1366, 768] # Display resolution 
fps = 30 # Frames per second
name = "Foo Bar"

[sessions]

    [sessions.Foo]
    url = "foo"
    day = "sat"
    time = "23:55"
    duration = 12 # in seconds
    prefix = "foo"
    saveDir = ""
    
    [sessions.Bar]
    url = "bar"
    day = "sat"
    time = "23:57"
    duration = 12
    prefix = "bar"
    saveDir = ""
    
